Upload interview XML documents
UTKcataloging/RFTA pull request #3
Opened 2022-02-16 21:38 UTC by logantillman

2022-02-17 14:58 UTC, markpbaggett commented
@logantillman and @mlhale7, 

Thanks for thinking about identifying the questions apart of each interview.  🥇

2022-02-17 16:37 UTC, mlhale7 requested changes

2022-02-17 16:37 UTC, mlhale7 commented on cleaned_data/loganXML/20220114_Braddock_Paige_edited.xml
> +   <name>
@logantillman - thanks so much for these records. Can you alter the name field here to the following:

```
<name authority="naf" valueURI="http://id.loc.gov/authorities/names/n2002022941">
      <namePart>Braddock, Paige</namePart>
      <role>
         <roleTerm authority="marcrelator"
                   valueURI="http://id.loc.gov/vocabulary/relators/ive">Interviewee</roleTerm>
      </role>
</name>
```
We don't always have authorities established in https://id.loc.gov, but we use them when we do.

2022-02-17 16:37 UTC, mlhale7 commented on cleaned_data/loganXML/20220114_Braddock_Paige_edited.xml
> +   </subject>
I've remembered that for our geographic information to be associated with a Browse category on rfta.lib.utk.edu we need to somewhat duplicate the geographic subject in another field. Can you add the following to all artist records (assuming they focus on Gatlinburg)?

`<note displayLabel="Browse">Gatlinburg, Sevierville and Pittman Center</note>`

2022-02-21 19:10 UTC, mlhale7 approved these changes
Thanks @logantillman - these look great.

2022-02-21 19:10 UTC, merged